### PR TITLE
solidify process spawning logic by taking an array of args

### LINKED ISSUE #42: Reimplement process spawning
**Describe the bug**
ionide/ionide-vscode-fsharp#1565 describes the problem, but the gist is the current string-based process spawning API hides some issues with paths that contain spaces.

We should refactor that api to take arrays of string arguments, and additionally consider using [cross-spawn](https://github.com/moxystudio/node-cross-spawn) to spawn processes in an xplat-compliant way. The readme on that repo has good points about why to use it instead of the bare spawn apis.

### PR DESCRIPTION
**Pull request by baronfel**
Fixes #42 by unifying a lot of the handling logic here, and using apis that take parameter arrays (which let the shell handle escaping.  This has been testing on an ionide branch that I'll send a PR up for shortly.

### CODE REVIEW

File: src/Helpers.fs [hunk 1]
```diff
@@ -20,34 +20,24 @@ module VSCode =
         |> Option.map (fun e -> e.extensionPath)
 
 
+module CrossSpawn =
```
Comment (baronfel) [inline src/Helpers.fs:23]: this does require adding the cross-spawn package, but that has to be handled on a consumer basis until/unless we package this repo as femto packages.

File: src/Helpers.fs [hunk 2]
```diff
@@ -73,59 +63,78 @@ module Process =
...
+        node.childProcess.spawn(command, args, options)
+
+    /// <summary>
+    /// Spawns a child process with a prefix command on linux if required.
+    /// </summary>
+    /// <param name="windowsCommand">the 'base' command to execute</param>
+    /// <param name="linuxCommand">if on linux, this runner command will be used as the command and the windowsCommand will be passed as the first parameter</param>
+    /// <param name="args">an array of additional CLI args</param>
+    /// <returns>a node child process</returns>
+    let spawn windowsCommand linuxCommand (args: ResizeArray<string>) =
```
Comment (Krzysztof-Cieslak) [inline src/Helpers.fs]: I wonder if we still need windows command vs linux command? Back in the days, we used that for windows .exe calls vs mono

Comment (baronfel) [reply src/Helpers.fs]: I think you're right here. every tool not uses `dotnet` as the runner, and the other places we do linux-specific things are entirely different calls to this API, because we're calling entirely different commands that don't follow the windows-prefix rules.
